### ISSUE TITLE
Mostrar apenas tempo restante no modo celular

### ISSUE THREAD

**Issue by eltonrios** [frescogo/frescogo#10]
No modo placar só temos o tempo restante, não seria melhor fazer assim também no celular???? E no formato 00:00.
No meu analfabetismo quase total de programação, fiz assim:

    Serial.print(F("Tempo Restante ..... "));
    if (((int)ceil((S.timeout-G.time)/(float)1000))/60 <10) {
      Serial.print(F("0"));
      Serial.print(G.time > S.timeout ? 0 : ((int)ceil((S.timeout-G.time)/(float)1000))/60);            
      } else {
      Serial.print(G.time > S.timeout ? 0 : ((int)ceil((S.timeout-G.time)/(float)1000))/60);
      }
   Serial.print(F(":")); 
   int segundos = ((((S.timeout-G.time)/(float)1000)/60)-(((int)ceil((S.timeout-G.time)/(float)1000))/60))*60;
   if (segundos < 10) {
        Serial.print(F("0"));
        Serial.println(segundos);
      } else {
        Serial.println(segundos);
      }

**Comment by fsantanna** [comment]
Feito
