### ISSUE TITLE
Distância no Placar

### ISSUE THREAD

**Issue by eltonrios** [frescogo/frescogo#25]
Com a opção de três opções de distância, acessadas através de um atalho de teclado, ocorrem duas coisas:
1. Quando o placar é carregado ele traz uma interrogação na distância, quando deveria trazer a distância que estiver setada no frescogo;
2. Após usar o atalho de velocodade, a qualquer momento em que o placar estiver em primeiro plano na tela, basta teclar ENTER para editar o nome do JUIZ;

**Comment by fsantanna-uerj** [comment]
2. Nem é necessário usar o atalho de velocidade.

**Comment by frescogo** [comment]
2.  Nem é necessário usar o atalho de velocidade.

**Comment by fsantanna-uerj** [comment]
2. Mudei para CTRL-A (Árbitro). O CTRL-J é equivalente ao ENTER (http://www.physics.udel.edu/~watson/scen103/ascii.html)

**Comment by fsantanna-uerj** [comment]
1. É mais complicado. Vamos ver se essa opção de escolher a distância vai vingar.

**Comment by frescogo** [comment]
resolvido na v2.3
