### ISSUE TITLE
Não registrar adição/remoção de quedas

### ISSUE THREAD

**Issue by eltonrios** [frescogo/frescogo#30]
Estes eventos deveriam constar no relatório do jogo.

**Comment by fsantanna** [comment]
Aparentemente já constam. Você chegou a testar?

**Comment by eltonrios** [comment]
Ok, realmente já consta tanto a adição quanto a subtração, somente o ato de retroceder uma sequência é que não vi registro, mas também não sei se seria esmo interessante que tivesse,

**Comment by fsantanna** [comment]
Vamos deixar sem isso por enquanto.
