### ISSUE TITLE
Erro no encerramento do tempo np PLACAR

### ISSUE THREAD

**Issue by eltonrios** [frescogo/frescogo#6]
marquei 3x um mesmo jogo (5 min), sempre dá erro qd encerra o tempo... não dá o fundo vermelho, não aparece o "aguarde", e os botões ficam mudos... e permite que eu saia a bola de novo.

**Comment by eltonrios** [comment]
sistematicamente, após o encerramento, o tempo retorna a 22 segundos restantes

**Comment by fsantanna** [comment]
E aí, isso está resolvido temporariamente com o 650?

**Comment by eltonrios** [comment]
Sim, com aumento dos HITS para 650 esse erro cessou.

**Comment by fsantanna** [comment]
Vou manter essa issue aberta.
A solução do `650` não é muito robusta, mas não tem muito de onde tirar memória do resto do programa.

**Comment by frescogo** [comment]
O jogo é encerrado sumariamente quando chegar no limite da memória.
Como a pontuação é pela média, e não pelo acúmulo de golpes, a dupla que chegar a esse limite não será prejudicada.
