### ISSUE TITLE
Informação dequem é a velocidade no celular

### ISSUE THREAD

**Issue by eltonrios** [frescogo/frescogo#8]
Nessemomento de enxugar bytes, não sei se isso seria conveniente (não sei que implicação teria nesta questão), mas seria interessante se no celular também se tivesse a informação de quem é a velocidade registrada (se do atleta da ESQUERDA ou DIREITA).
Se possível, poderia ficar assim:
> saque
E 29
D 56
E 57
D 62

Ou então assim:
> saque
> 29
>    56
> 57
>    62

**Comment by eltonrios** [comment]
Na segunda sugestão não deu para apresentar aqui, mas seria deslocar tres campos para a direita todas as velocidade do atleta à DIREITA.
O sinal de ">" (maior) também digitei mas sumiu aqui no nesse editor

**Comment by eltonrios** [comment]
> saque
29
   56
57
    62

**Comment by fsantanna** [comment]
Feito!
